In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
np.array(mylist)

array([1, 2, 3])

In [5]:
mylist

[1, 2, 3]

In [6]:
myarr = np.array(mylist)

In [7]:
type(myarr)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,101,20)#third is a step size

array([  0,  20,  40,  60,  80, 100])

In [12]:
np.zeros(5)#just produce folating in a row

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,5))#first row second is a column

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.linspace(0,10,21)#how many numbers do you want at third part 

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [16]:
len(np.linspace(0,10,21))

21

In [17]:
np.eye(5)#numpy identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand(5,2) # if you enter two things first row second column and it provide
#random number between 0-1

array([[0.00789897, 0.5297394 ],
       [0.99289859, 0.13700453],
       [0.76743242, 0.5143152 ],
       [0.86755851, 0.93850673],
       [0.18049877, 0.34385274]])

In [19]:
np.random.randn(10)

array([ 0.9615289 , -1.04118989,  1.38898872, -0.34002286, -0.22295709,
       -0.60789966,  0.04381128,  1.68546835,  1.57110479,  0.28794223])

In [20]:
np.random.randn(2,3)

array([[ 2.27666614, -0.90247201,  0.80631539],
       [-1.48276178,  0.82272817, -1.59026944]])

In [21]:
np.random.randint(0,101,5)#third is a size of integers 

array([15, 42, 74, 72, 88])

In [22]:
np.random.randint(0,101,(4,5))

array([[59, 73, 81, 83, 76],
       [23, 10, 64, 98, 61],
       [ 8, 12,  2, 79, 20],
       [ 5, 78,  4, 58, 51]])

In [23]:
np.random.seed(42)# if you use seed your random numder is fixed 
#if you change your seed number you can also fixed different random number 
#seed is important to future learning to test your code with seed numbers
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
arr = np.arange(0,25)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [27]:
ranarr = np.random.randint(0,101,10)

In [28]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [29]:
ranarr.max()

99

In [30]:
ranarr.min()

2

In [31]:
ranarr.argmax()

5

In [32]:
ranarr.argmin()

7

In [33]:
ranarr.dtype

dtype('int32')

In [34]:
arr.shape

(25,)

In [35]:
arr = arr.reshape(5,5)

In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr.shape

(5, 5)

In [41]:
arr.reshape(25,1)#attention the brackets 

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])